# Generated by Django 4.1.7 on 2023-03-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status_price',
            field=models.CharField(choices=[('discount 75', 'Discount 75%'), ('discount 50', 'Discount 50%'), ('discount 35', 'Discount 35%'), ('discount 10', 'Discount 10%')], default='discount 10', max_length=50),
        ),
    ]
